#ifdef SSCYIELD_COUNT
#	if SSCYIELD_COUNT == -1
#		define SSCYIELD_COUNT 0
SSCCORO_LABEL_0:
#	elif SSCYIELD_COUNT == 0
#		define SSCYIELD_COUNT 1
SSCCORO_LABEL_1 :
#	elif SSCYIELD_COUNT == 1
#		define SSCYIELD_COUNT 2
SSCCORO_LABEL_2 :
#	elif SSCYIELD_COUNT == 2
#		define SSCYIELD_COUNT 3
SSCCORO_LABEL_3 :
#	elif SSCYIELD_COUNT == 3
#		define SSCYIELD_COUNT 4
SSCCORO_LABEL_4 :
#	elif SSCYIELD_COUNT == 4
#		define SSCYIELD_COUNT 5
SSCCORO_LABEL_5 :
#	elif SSCYIELD_COUNT == 5
#		define SSCYIELD_COUNT 6
SSCCORO_LABEL_6 :
#	elif SSCYIELD_COUNT == 6
#		define SSCYIELD_COUNT 7
SSCCORO_LABEL_7 :
#	elif SSCYIELD_COUNT == 7
#		define SSCYIELD_COUNT 8
SSCCORO_LABEL_8 :
#	elif SSCYIELD_COUNT == 8
#		define SSCYIELD_COUNT 9
SSCCORO_LABEL_9 :
#	elif SSCYIELD_COUNT == 9
#		define SSCYIELD_COUNT 10
SSCCORO_LABEL_10 :
#	elif SSCYIELD_COUNT == 10
#		define SSCYIELD_COUNT 11
SSCCORO_LABEL_11 :
#	elif SSCYIELD_COUNT == 11
#		define SSCYIELD_COUNT 12
SSCCORO_LABEL_12 :
#	elif SSCYIELD_COUNT == 12
#		define SSCYIELD_COUNT 13
SSCCORO_LABEL_13 :
#	elif SSCYIELD_COUNT == 13
#		define SSCYIELD_COUNT 14
SSCCORO_LABEL_14 :
#	elif SSCYIELD_COUNT == 14
#		define SSCYIELD_COUNT 15
SSCCORO_LABEL_15 :
#	elif SSCYIELD_COUNT == 15
#		define SSCYIELD_COUNT 16
SSCCORO_LABEL_16 :
#	elif SSCYIELD_COUNT == 16
#		define SSCYIELD_COUNT 17
SSCCORO_LABEL_17 :
#	elif SSCYIELD_COUNT == 17
#		define SSCYIELD_COUNT 18
SSCCORO_LABEL_18 :
#	elif SSCYIELD_COUNT == 18
#		define SSCYIELD_COUNT 19
SSCCORO_LABEL_19 :
#	elif SSCYIELD_COUNT == 19
#		define SSCYIELD_COUNT 20
SSCCORO_LABEL_20 :
#	elif SSCYIELD_COUNT == 20
#		define SSCYIELD_COUNT 21
SSCCORO_LABEL_21 :
#	elif SSCYIELD_COUNT == 21
#		define SSCYIELD_COUNT 22
SSCCORO_LABEL_22 :
#	elif SSCYIELD_COUNT == 22
#		define SSCYIELD_COUNT 23
SSCCORO_LABEL_23 :
#	elif SSCYIELD_COUNT == 23
#		define SSCYIELD_COUNT 24
SSCCORO_LABEL_24 :
#	elif SSCYIELD_COUNT == 24
#		define SSCYIELD_COUNT 25
SSCCORO_LABEL_25 :
#	elif SSCYIELD_COUNT == 25
#		define SSCYIELD_COUNT 26
SSCCORO_LABEL_26 :
#	elif SSCYIELD_COUNT == 26
#		define SSCYIELD_COUNT 27
SSCCORO_LABEL_27 :
#	elif SSCYIELD_COUNT == 27
#		define SSCYIELD_COUNT 28
SSCCORO_LABEL_28 :
#	elif SSCYIELD_COUNT == 28
#		define SSCYIELD_COUNT 29
SSCCORO_LABEL_29 :
#	elif SSCYIELD_COUNT == 29
#		define SSCYIELD_COUNT 30
SSCCORO_LABEL_30 :
#	elif SSCYIELD_COUNT == 30
#		define SSCYIELD_COUNT 31
SSCCORO_LABEL_31 :
#	elif SSCYIELD_COUNT == 31
#		define SSCYIELD_COUNT 32
SSCCORO_LABEL_32 :
#	elif SSCYIELD_COUNT == 32
#		define SSCYIELD_COUNT 33
SSCCORO_LABEL_33 :
#	elif SSCYIELD_COUNT == 33
#		define SSCYIELD_COUNT 34
SSCCORO_LABEL_34 :
#	elif SSCYIELD_COUNT == 34
#		define SSCYIELD_COUNT 35
SSCCORO_LABEL_35 :
#	elif SSCYIELD_COUNT == 35
#		define SSCYIELD_COUNT 36
SSCCORO_LABEL_36 :
#	elif SSCYIELD_COUNT == 36
#		define SSCYIELD_COUNT 37
SSCCORO_LABEL_37 :
#	elif SSCYIELD_COUNT == 37
#		define SSCYIELD_COUNT 38
SSCCORO_LABEL_38 :
#	elif SSCYIELD_COUNT == 38
#		define SSCYIELD_COUNT 39
SSCCORO_LABEL_39 :
#	elif SSCYIELD_COUNT == 39
#		define SSCYIELD_COUNT 40
SSCCORO_LABEL_40 :
#	elif SSCYIELD_COUNT == 40
#		define SSCYIELD_COUNT 41
SSCCORO_LABEL_41 :
#	elif SSCYIELD_COUNT == 41
#		define SSCYIELD_COUNT 42
SSCCORO_LABEL_42 :
#	elif SSCYIELD_COUNT == 42
#		define SSCYIELD_COUNT 43
SSCCORO_LABEL_43 :
#	elif SSCYIELD_COUNT == 43
#		define SSCYIELD_COUNT 44
SSCCORO_LABEL_44 :
#	elif SSCYIELD_COUNT == 44
#		define SSCYIELD_COUNT 45
SSCCORO_LABEL_45 :
#	elif SSCYIELD_COUNT == 45
#		define SSCYIELD_COUNT 46
SSCCORO_LABEL_46 :
#	elif SSCYIELD_COUNT == 46
#		define SSCYIELD_COUNT 47
SSCCORO_LABEL_47 :
#	elif SSCYIELD_COUNT == 47
#		define SSCYIELD_COUNT 48
SSCCORO_LABEL_48 :
#	elif SSCYIELD_COUNT == 48
#		define SSCYIELD_COUNT 49
SSCCORO_LABEL_49 :
#	elif SSCYIELD_COUNT == 49
#		define SSCYIELD_COUNT 50
SSCCORO_LABEL_50 :
#	elif SSCYIELD_COUNT == 50
#		define SSCYIELD_COUNT 51
SSCCORO_LABEL_51 :
#	elif SSCYIELD_COUNT == 51
#		define SSCYIELD_COUNT 52
SSCCORO_LABEL_52 :
#	elif SSCYIELD_COUNT == 52
#		define SSCYIELD_COUNT 53
SSCCORO_LABEL_53 :
#	elif SSCYIELD_COUNT == 53
#		define SSCYIELD_COUNT 54
SSCCORO_LABEL_54 :
#	elif SSCYIELD_COUNT == 54
#		define SSCYIELD_COUNT 55
SSCCORO_LABEL_55 :
#	elif SSCYIELD_COUNT == 55
#		define SSCYIELD_COUNT 56
SSCCORO_LABEL_56 :
#	elif SSCYIELD_COUNT == 56
#		define SSCYIELD_COUNT 57
SSCCORO_LABEL_57 :
#	elif SSCYIELD_COUNT == 57
#		define SSCYIELD_COUNT 58
SSCCORO_LABEL_58 :
#	elif SSCYIELD_COUNT == 58
#		define SSCYIELD_COUNT 59
SSCCORO_LABEL_59 :
#	elif SSCYIELD_COUNT == 59
#		define SSCYIELD_COUNT 60
SSCCORO_LABEL_60 :
#	elif SSCYIELD_COUNT == 60
#		define SSCYIELD_COUNT 61
SSCCORO_LABEL_61 :
#	elif SSCYIELD_COUNT == 61
#		define SSCYIELD_COUNT 62
SSCCORO_LABEL_62 :
#	elif SSCYIELD_COUNT == 62
#		define SSCYIELD_COUNT 63
SSCCORO_LABEL_63 :
#	endif
#else
#error No Include SSCCORO_BEGIN()
#endif
